import type { Metadata } from "next";

import "./globals.css";
import Head from "@/components/Head";
import Footer from "@/components/Footer";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins antialiased">
        <Head />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
